### ISSUE TITLE
Update Dependencies for 2024

### ISSUE THREAD

**Issue by starmorph** [stevenpersia/tinder-expo#10]
1. Clone Repo
2. Yarn add expo
3. npx expo install --check 
4. Select Y to update dependencies
5.  Add icon file to tinder-expo/assets/images

These steps got this repo working for me despite all the framework/dependencies changes in the past 2 years. hope this helps others trying to get this app working.

**Comment by ChefMC** [comment]
Hi, which icon do you mean on step 5?

**Comment by ChefMC** [comment]
And which Node.js version do you use? Thank you

**Comment by ChefMC** [comment]
```
Running application "main" with appParams:
 Object 
Development-level warnings: ON.
Performance optimizations: OFF.
D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:22841 Uncaught TypeError: _this$contentRef$curr.setNativeProps is not a function
    at Card.setPointerEventsEnabled (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:125:9)
    at Card.animate (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:76:7)
    at Card.componentDidMount (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:264:7)
    at commitLayoutEffectOnFiber (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:23307:21)
    at commitLayoutMountEffects_complete (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24690:9)
    at commitLayoutEffects_begin (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24676:3)
    at commitLayoutEffects (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24614:3)
    at commitRootImpl (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:26825:5)
    at commitRoot (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:26684:5)
    at finishConcurrentRender (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:25983:7)
D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:18689 The above error occurred in the <Card> component:

    at Card (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:61003:7)
    at CardContainer (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:60718:7)
    at div
    at http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:34912:27
    at MaybeScreen (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:59204:7)
    at div
    at http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:34912:27
    at MaybeScreenContainer (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:59187:7)
    at CardStack (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:58272:7)
    at KeyboardManager (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:63447:7)
    at div
    at http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:34912:27
    at NativeSafeAreaProvider (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:57871:7)
    at SafeAreaProvider (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:57738:7)
    at SafeAreaProviderCompat (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:64271:7)
    at div
    at http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:34912:27
    at StackView (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:57304:7)
    at StackNavigator (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:57195:7)
    at EnsureSingleNavigator (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:51470:7)
    at BaseNavigationContainer (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:51199:7)
    at ThemeProvider (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:55139:7)
    at NavigationContainer (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:55076:7)
    at App
    at withDevTools(App)
    at AppContainer (http://localhost:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:29727:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:18689
Показать ещё 1 фрейм
Свернуть
D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:12058 Uncaught TypeError: _this$contentRef$curr.setNativeProps is not a function
    at Card.setPointerEventsEnabled (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:125:9)
    at Card.animate (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:76:7)
    at Card.componentDidMount (D:\Dev\IdeaProjects\tinder-expo\node_modules\@react-navigation\stack\lib\module\views\Stack\Card.js:264:7)
    at commitLayoutEffectOnFiber (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:23307:21)
    at commitLayoutMountEffects_complete (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24690:9)
    at commitLayoutEffects_begin (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24676:3)
    at commitLayoutEffects (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:24614:3)
    at commitRootImpl (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:26825:5)
    at commitRoot (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:26684:5)
    at finishConcurrentRender (D:\Dev\IdeaProjects\tinder-expo\node_modules\react-dom\cjs\react-dom.development.js:25983:7)
```
